---
name: Release Please
on:
  workflow_call:
    inputs:
      release-type:
        type: string
        default: simple
      manifest-file:
        type: string
        description: path to the release-please versions manifest
        default: .release-please-manifest.json
    secrets:
      STATNETT_BOT_APP_ID:
        required: true
      STATNETT_BOT_PRIVATE_KEY:
        required: true
    outputs:
      releases_created:
        description: true if the release was created, false otherwise
        value: ${{ jobs.release-please.outputs.releases_created }}
      major:
        description: Number representing major semver value
        value: ${{ jobs.release-please.outputs.major }}
      minor:
        description: Number representing minor semver value
        value: ${{ jobs.release-please.outputs.minor }}
      patch:
        description: Number representing patch semver value
        value: ${{ jobs.release-please.outputs.patch }}
      sha:
        description: sha that a GitHub release was tagged at
        value: ${{ jobs.release-please.outputs.sha }}

permissions: {}
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      sha: ${{ steps.release.outputs.sha }}
    steps:
      - id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.STATNETT_BOT_APP_ID }}
          private_key: ${{ secrets.STATNETT_BOT_PRIVATE_KEY }}

      - id: release
        uses: google-github-actions/release-please-action@a2d8d683f209466ee8c695cd994ae2cf08b1642d # v4.0.1
        with:
          manifest-file: ${{ inputs.manifest-file }}
          release-type: ${{ inputs.release-type }}
          token: ${{ steps.token.outputs.token }}
